# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 548cc83022c0fbfc523b04c3b9ae9ebc3ca694991cd1a01fbd59f2eb3a0b64ce5a5c4bf0751336107c4587dc77c307d16d6224d5721e08c8eb0cec4c735d43d7

test:
  secret_key_base: a075d636c018bd6465e2a1a775101af4b7b7430b5ebae10a23df17259385a5b5eb2d4a6e9b62530d366cf99c2508d3e4de8bd5975a607b83bf0fb1e6c0b366e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
